import { AUTHOR, OG_IMAGE, SITE_URL, absoluteUrl } from "@/lib/site";
import { homepageFaqs } from "@/data/faqs";

const areaServed = [
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "Germany",
  "Switzerland",
  "Netherlands",
  "United Arab Emirates",
  "Saudi Arabia",
  "Pakistan",
];

export function getHomepageSchema() {
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebSite",
        "@id": `${SITE_URL}/#website`,
        url: `${SITE_URL}/`,
        name: "Malik Taleeb Shahbaz | Software & Web Developer",
        description:
          "Full stack software developer offering custom web development, POS systems, SaaS applications, CRM development, and SEO-friendly business websites for global clients.",
        inLanguage: "en",
        publisher: { "@id": `${SITE_URL}/#organization` },
      },
      {
        "@type": "Organization",
        "@id": `${SITE_URL}/#organization`,
        name: "Malik Taleeb Shahbaz | Software Development",
        url: SITE_URL,
        logo: absoluteUrl(OG_IMAGE),
        founder: { "@id": `${SITE_URL}/#person` },
        description:
          "Software development and web development services — custom business websites, POS systems, SaaS, CRM, and SEO-optimized builds worldwide.",
        areaServed,
        knowsAbout: [
          "Software Development",
          "Web Development",
          "Custom Software Development",
          "POS System Development",
          "SaaS Development",
          "CRM Development",
          "React",
          "Next.js",
          "JavaScript",
          "SEO",
        ],
      },
      {
        "@type": "Person",
        "@id": `${SITE_URL}/#person`,
        name: AUTHOR.name,
        jobTitle: AUTHOR.jobTitles,
        url: SITE_URL,
        description:
          "Malik Taleeb Shahbaz is a software developer and web developer in Abbottabad, Pakistan who builds custom websites, POS systems, SaaS applications, and business management software for startups and companies worldwide.",
        image: absoluteUrl("/assets/home/taleeb.webp"),
        address: {
          "@type": "PostalAddress",
          addressLocality: "Abbottabad",
          addressCountry: "PK",
        },
        worksFor: { "@type": "Organization", name: AUTHOR.worksFor },
        knowsAbout: [
          "Software Development",
          "Web Development",
          "Full Stack Development",
          "Frontend Development",
          "Backend Development",
          "Custom Software Development",
          "POS System Development",
          "Point of Sale Software",
          "Inventory Management System",
          "School Management System",
          "Business Management Software",
          "CRM Development",
          "ERP Development",
          "SaaS Development",
          "API Development",
          "Database Design",
          "React",
          "Next.js",
          "Vue.js",
          "Node.js",
          "JavaScript",
          "TypeScript",
          "E-commerce Website Development",
          "Responsive Website Design",
          "SEO Friendly Website Development",
          "Website Maintenance",
          "Website Redesign",
        ],
        sameAs: [
          "https://github.com/mtaleebshahbaz",
          "https://www.linkedin.com/in/malik-taleeb-shahbaz-138769342",
          "https://www.instagram.com/malik.taleeb.7/",
        ],
      },
      {
        "@type": "ProfessionalService",
        "@id": `${SITE_URL}/#service`,
        name: "Malik Taleeb Shahbaz | Software & Web Development Services",
        url: `${SITE_URL}/#services`,
        description:
          "Custom software development, web development, POS systems, SaaS applications, CRM development, React/Next.js apps, e-commerce websites, and SEO-friendly business sites.",
        provider: { "@id": `${SITE_URL}/#person` },
        areaServed: areaServed.map((name) => ({ "@type": "Country", name })),
        serviceType: [
          "Software Development",
          "Web Development",
          "Custom Website Development",
          "Custom Software Development",
          "Custom Web Applications",
          "POS System Development",
          "Point of Sale Software",
          "Inventory Management System",
          "School Management System",
          "Business Management Software",
          "CRM Development",
          "ERP Development",
          "SaaS Development",
          "API Development",
          "E-commerce Website Development",
          "Company Website Development",
          "Full Stack Development",
          "Frontend Development",
          "React Development",
          "Next.js Development",
          "SEO Friendly Website Development",
          "Website Maintenance",
          "Website Redesign",
          "Responsive Website Design",
        ],
      },
      {
        "@type": "BreadcrumbList",
        "@id": `${SITE_URL}/#breadcrumb`,
        itemListElement: [
          {
            "@type": "ListItem",
            position: 1,
            name: "Home",
            item: `${SITE_URL}/`,
          },
        ],
      },
      {
        "@type": "FAQPage",
        "@id": `${SITE_URL}/#faq`,
        mainEntity: homepageFaqs.map((faq) => ({
          "@type": "Question",
          name: faq.question,
          acceptedAnswer: { "@type": "Answer", text: faq.answer },
        })),
      },
    ],
  };
}
